#开发配置
spring:
  datasource:
    url: jdbc:mysql://106.12.127.137:3306/smse?setUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
