#开发配置
#spring:
#  datasource:
#    url: jdbc:mysql://106.12.127.137:3306/smse?setUnicode=true&characterEncoding=utf8
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource

thymeleaf:
  cache: false


#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**